### ISSUE TITLE
Creazione pagina Home lato utente

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#1]
![image](https://user-images.githubusercontent.com/56229661/66669552-14b20900-ec58-11e9-98ac-cf439c48c16f.png)

**Comment by Mirco469** [comment]
Ho aperto un paio di siti di sushi e tutti hanno come home una galleria di immagini grande tutto lo schermo che scorrono. Oltre al menu in cima poi si può scrollare e li poi ci sono varie informazioni tipo "Chi siamo" e "Dove sono i ristoranti". Siccome noi abbiamo già queste pagine a se stanti dovremmo prendere in considerazione se mettere tutto nella home oppure fare la home con solo le immagini che scorrono (io sarei più per la seconda).
