### ISSUE TITLE
Validazione W3C

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#101]
Validare tutte le pagine in xhtml1.0 o html5 
Quando aggiungerò la label **W3C Validated** allora saranno tutte pronte per la release

PS: Se riuscite provate a testare le pagine

**Comment by Mirco469** [comment]
Validato tutto, unico warning che da è questo
![image](https://user-images.githubusercontent.com/56229661/67639374-46310280-f8ef-11e9-897f-32deeb142a56.png)
