### ISSUE TITLE
Modifiche pagine

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#104]
Io aggiungerei il link torna su nella **pagina prodotti** e modificherei il testo del link torna sù nella **pagina take away** togliendo la u accentata

**Comment by Mirco469** [comment]
Riguardo alla pagina prodotto io prima vedrei come viene fuori con il css perchè secondo me una volta che hai rimpicciolito quelle foto il testo magari va affianco delle foto e diventa corta la pagina
