### ISSUE TITLE
Creazione pagina di AggiuntaProdotti

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#14]
![image](https://user-images.githubusercontent.com/56229661/66670055-221bc300-ec59-11e9-88f0-7f71c8ffb831.png)

**Comment by Mirco469** [comment]
Io qui pensavo in cima un form che ti permette di mettere un nome del prodotto, il prezzo e a che categoria associarlo di quelle già esistenti e sotto una lista con i prodotti già presenti magari con la possibilità di eliminarli e modificarli, voi cosa pensavate?
Qualcosa del genere:
![image](https://user-images.githubusercontent.com/56229661/66704640-21009980-ed1e-11e9-8069-56ce24476d88.png)

**Comment by aletomm** [comment]
Mi sembra una buona idea.
