### ISSUE TITLE
Fare tabindex lato utente

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#151]

**Comment by aletomm** [comment]
Come assegno l'indice dei tab nel menù a tendina? 
Invece come devo fare nel caso login / impostazioni?

**Comment by Mirco469** [comment]
Nella tendina se si può fare io lo farei andare solo sul pulsante principale quello che clicchi per aprire la tendina. Nel caso login/impostazioni io metterei lo stesso indice visto che c'è o uno o l'altro sempre se possibile.
