### ISSUE TITLE
Fieldset sbagliato

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#156]
Leggendo su w3school dice questo sui fieldset: "The fieldset tag is used to group related elements in a form." In questo caso non mi sembra sia corretto usarlo o sbaglio?
https://github.com/Mirco469/ProgettoSushi/blob/3f29713f0c34775ff295ecb468d80bd5bbf83ab3/recensioni.html#L46-L58

**Comment by aledindinelli** [comment]
Vero grazie. Forse l'avevo messo solo perchè visivamente mi delimitava l'area dove pensavo di mettere le recensioni già scritte. Lo tolgo.
