### ISSUE TITLE
Sistemare problema footer

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#158]
Cosa fare con quella riga nera sotto il footer?
![image](https://user-images.githubusercontent.com/56229661/68603328-5c6ebf00-04a8-11ea-8790-226d18607c4a.png)

**Comment by aledindinelli** [comment]
Su Stackoverflow c'e questo https://stackoverflow.com/questions/34188161/remove-white-space-below-footer.
Consigliano o di dare un'altezza minima al content, o una risposta più sotto dice di usare del javascript, ma ancora non so usarlo.

**Comment by Mirco469** [comment]
Eh ma dare un'altezza minima magari va bene per il mio schermo ma non per altri..non mi sembra una buona soluzione

**Comment by Mirco469** [comment]
Come fatto notare da Alessandro D. il sito della Gaggi ha lo stesso problema.

**Comment by nfrison** [comment]
Io lascierei così e chiuderei la issue
