### ISSUE TITLE
Popolare il database

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#163]
Il file sql per creare il database è già fatto (si trova in documentazione) ma bisogna popolarlo. Per una guida su come popolare il database ecco il vecchio file del progetto di basi: [CreazioneTabellev1.0.zip](https://github.com/Mirco469/ProgettoSushi/files/3832875/CreazioneTabellev1.0.2.zip)

**Comment by aledindinelli** [comment]
Se può essere utile, questo è il mio file del progetto di Basi di Dati.
[FidasDatabase.zip](https://github.com/Mirco469/ProgettoSushi/files/3880294/FidasDatabase.zip)
