### ISSUE TITLE
Controllare sito per colorblind

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#170]
www.vischeck.com
Controllare che chi ha problemi di vista (tipo daltonici) se i link assumono colore simile tra cliccato e non cliccato.

**Comment by aletomm** [comment]
![Schermata 2019-12-03 alle 12 03 11](https://user-images.githubusercontent.com/40260964/70045764-f10a9f80-15c4-11ea-94e5-3af44178e805.png)
![Schermata 2019-12-03 alle 12 03 23](https://user-images.githubusercontent.com/40260964/70045766-f10a9f80-15c4-11ea-8c5a-8b7a42aa1a8f.png)
