### ISSUE TITLE
Aggiungere lang

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#193]
Aggiungere l'attributo lang oltre a xml:lang su tutte le pagine xhtml1.0.

**Comment by aledindinelli** [comment]
Intendi nel tag <html> ad inizio pagina o in tutti i tag?

**Comment by Mirco469** [comment]
Dovunque ci sia un xml:lang bisogna mettere anche lang perchè facendo il test con lo screen reader non legge la parola in inglese se non c'è lang..insomma credo che xml:lang sia inutile ma lasciamolo visto che la prof non ci ha detto niente

**Comment by aledindinelli** [comment]
Ok
