### ISSUE TITLE
Rimuovere bottoni e altri elementi dal CSS Stampa

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#235]
Secondo voi è necessario rimuovere tutti i bottoni e/o campi editabili nella stampa delle pagine o non serve?

**Comment by Mirco469** [comment]
Eh ma se ci sono elementi editabili e uno cerca di stampare la pagina forse è perchè vuole proprio quei campo (faccio ad esempio la pagina di login). Forse in certe pagine si può fare perchè sono inutili allo scopo della pagina ma ora non me ne vengono in mente. Tu che pagine intendevi?

**Comment by aledindinelli** [comment]
Nella pagina di pagamento, in fondo, ci sono due bottoni (indietro e paga), secondo voi li tengo?

**Comment by Mirco469** [comment]
Secondo me si così se uno stampa sa che da quella pagina si può proseguire e pagare. Le uniche cose che secondo me bisogna ragionare sono magari alcune immagini se ce ne sono per il resto i bottoni secondo me sono parte del contenuto
