### ISSUE TITLE
Creazione header, footer e menù 

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#24]
Secondo me sarebbe meglio fare ciò che ho scritto nel titolo direttamente nel branch develop, così tutti possono copiarle da lì, cosa ne pensate?

**Comment by Mirco469** [comment]
Io comunque lo farei in un branch a posta e appena è finito lo unirei perchè sennò se non fai il menu tutto in un colpo escono 2/3 commit per finire ogni volta il menu o forse non ho capito?

**Comment by aletomm** [comment]
Ok, va bene
Dobbiamo decidere cosa metterci di preciso nel footer 
Ho visto che di solito ripetono l'indirizzo, il numero di telefono e noi potremmo metterci anche la certificazione per il css e l'xhtml

**Comment by Mirco469** [comment]
Mi sembra vada benissimo, magari vediamo cosa ci dice in laboratorio quando arriviamo a fare il footer
