### ISSUE TITLE
Uniformare database e pagina dettagli ordine

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#266]
- Il database non ha la data di consegna. Motivazione di Alessandro: In Ordine, ho tolto l'attributo data_consegna visto che nella pagina di successo diciamo che l'ordine arriverà entro un'ora. Penso basti accennare nella recensione che assumiamo che la spedizione vada a buon fine.
- La pagina di dettagli ordine invece ha la data di consegna. Motivazione di Fritz: In generale è più logico metterle entrambe. Poi noi perché è un progetto le mettiamo una un'ora dopo l'altra

Bisogna uniformare le due cose. Discussione su quale fare.

**Comment by aledindinelli** [comment]
Si in effetti avevo guardato solo com'è il sito nostro ma in generale ha senso. Ho visto che esiste oltre al formato DATE, anche il DATETIME che tiene la data e l'ora in formato 'YYYY-MM-DD hh:mm:ss'. Quale delle due volete usare?

**Comment by Mirco469** [comment]
Se dobbiamo avere entrambe data di ordine e di consegna a questo punto andrei su quella con il tempo. Hai quindi deciso di andare per averpe entrambe?

**Comment by aledindinelli** [comment]
Si, se va bene a tutti possiamo tenere entrambe le date per rappresentare di più la realtà.
Vi chiedevo, perchè non saprei dire se il DATETIME è problematico da usare. Nel senso che non sapendo come funziona il backend, non so se sia facile o difficile da implementare il salvataggio della data e ora.

**Comment by Mirco469** [comment]
Ho appena parlato con Fritz e ha detto che non è difficile da fare. Ti ho quindi scritto sulla pull request di mettere DATETIME
