### ISSUE TITLE
Uniformare tabella pagina aggiunta prodotti

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#275]
Uniformare con tabella di fritz. Cambiare il nome della classe in defaultTable e modificarne il riferimento su tutte le pagine. **Aspettare che Fritz riceva risposta dalla prof riguardo gli header non delineati chiaramente.**

**Comment by nfrison** [comment]
![Screenshot_20191129-135715_Gmail](https://user-images.githubusercontent.com/56256087/69870578-9dd8da00-12b0-11ea-8660-d7aec6883905.jpg)

**Comment by Mirco469** [comment]
Grande @nfrison di sicuro con questo screen gli utenti con dislessia non avranno problemi xD
