### ISSUE TITLE
Riguardare pagina contatti per punto di rottura

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#278]
L'immagine di google maps e il testo a fianco.
![image](https://user-images.githubusercontent.com/56229661/69814879-72dd8000-11f5-11ea-85fe-049b8f8bc22c.png)

**Comment by aledindinelli** [comment]
https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints/
