### ISSUE TITLE
Controllare dimensione e stile dei bottoni da windows 

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#331]
Controllare dimensione e stile dei bottoni da windows nel css dei form

**Comment by Mirco469** [comment]
Non so cosa voglia dire ma non c'è nessuna pagina che ha un form e il cui css per lo smartphone sia stato fatto il merge nel develop. Se hai un branch in particolare che devo vedere dimmi e ti invio lo screen.

**Comment by Mirco469** [comment]
@aletomm Controlla come si vede sul tuo pc
Windows: 
![image](https://user-images.githubusercontent.com/56229661/70236748-d7ed2480-1765-11ea-9738-e4ed3c1ebbee.png)
