### ISSUE TITLE
Fare una lista dei tag in comune

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#341]
Fare una lista dei tag in comune delle varie tipo di pagine. Vedere che insiemi di tag comuni si possono usare per dividere i tag in comune(lato utente?, lato admin? oppure HTML5?, XHTML1.0? o altri tipi non saprei)

**Comment by aletomm** [comment]
[tagInComune.txt](https://github.com/Mirco469/ProgettoSushi/files/3926048/tagInComune.txt)
