### ISSUE TITLE
Revisione testing Pagine per mobile DA FINIRE

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#401]
Fix da fare:

Aggiungere torna su nella pagina delle recensioni.html 
Aggiungere torna su nella pagina prodotti.html
torna su home_utente
torna su chi_siamo
torna su contatti
torna su carrello
torna su gestione_profilo
torna su storico_ordini
Mettere margin-top button nella pagina gestione_profilo utente (anche desktop)
Torna su home_admin
Torna su aggiungi_prodotto
Torna su gestione_ordini

 

Cose da chiedere alla prof: 

1. Tabella carrello.html e gestione_ordini.html

**Comment by aledindinelli** [comment]
Nella pagina TakeAway l'avevo fatto così:
`<div id="torna_su">`
`<a href="#header">Torna su</a>`
`</div>`
Se c'è da cambiargli nome basta poi ricordarsi di cambiarlo anche nei css.
