### ISSUE TITLE
Modificare tabelle che non ci stanno

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#403]
Le tabelle troppo larghe non ci stanno sul cellulare e fanno scroll orizzontale. Modificarle, vedere se va bene la bozza nel branch modificaTabelle della pagina carrello.

**Comment by aletomm** [comment]
Ho dato un'occhiata alle tabelle e mi sembra che vadano tutte bene 
Alla fine quelle che sono rimaste (storico_ordini e dettagli_ordine) non danno scroll orizzontali sul mio cellulare
