### ISSUE TITLE
Non esiste una tabella per le carte di credito 

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#406]
Facendo le query nella pagina php ho notato che non esiste una tabella per le carte di credito. 
Vengono memorizzate tutte in utente
Facendo in questo modo non diventa impossibile per l'utente avere più di una carta per account?

**Comment by Mirco469** [comment]
Non era il nostro obiettivo fargli avere solo una carta di credito ma più indirizzi di destinazione? PS: prima di fare le pagine php per favore finiamo sto benedetto sito mentre è statico

**Comment by aledindinelli** [comment]
Volendo nella relazione, come diceva la Gaggi, possiamo dire che abbiamo messo al massimo una carta per utente, ma che dato il tipo di sito in futuro sarebbe tra le aggiunte che si potrebbbero fare.

**Comment by aletomm** [comment]
Va bene, stavo provando a fare un po' di php solo per esercitarmi 
Ah avete ragione, scusatemi
