### ISSUE TITLE
PHP pagina aggiunta prodotti

### ISSUE THREAD

**Issue by Mirco469** [Mirco469/ProgettoSushi#427]
**aspettare #456**

**Comment by nfrison** [comment]
Io pensavo di aggiungere i prodotti a sessione in questo modo:

In sessione mettere la chiave 'carrello' a cui mettere come valore un array, e dentro a questo array pushare i prodotti con i seguenti campi: 'nome', 'categoria', 'quantita', 'prezzo' (dove prezzo intendo quello unitario)

Struttura:
$_SESSION['carrello'] = array(
0 => array(
'nome' => /*nome*/,
'categoria' => /*categoria*/,
'quantita' => /*quantita*/,
'prezzo' => /*prezzo per porzione*/,
)
)

Dimmi che ne pensi
