### ISSUE TITLE
PROBLEMA Menu utente!

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#45]
Mi sono accorto che nel fare il menu per l'utente ho messo la parola Carrello fuori dal tag <a></a>. Ho già provveduto a cambiare il file base_utente.html però se avete già copiato il codice correggete anche voi.
Grazie e scusatemi ancora

**Comment by Mirco469** [comment]
Ok, grazie e per fortuna che te ne sei accorto :D

**Comment by nfrison** [comment]
Ottimo

**Comment by Mirco469** [comment]
Aspe ma ho notato che avete modificato un sacco baseUtente ma quel branch deve essere cancellato ormai abbiamo fatto il merge con il develop D: Io quindi adesso dovrei prendere i file dal branch? Conviene fare un merge nel caso e cancellare quei branch definitivamente prima che qualcun'altro si metta a modifacare
