### ISSUE TITLE
Cambiamento HEADER e BREADCRUMB

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#51]
Dopo la lezione di oggi avevo pensato che potremmo **togliere l'immagine del logo** (ovvero solo il tag `<img>...</img>` ) e metterci al suo posto `<span id="logo"></span>`, aggiungendo poi l'immagine via CSS.
Inoltre pensavo di uniformarci con i breadcrumb scrivendo tutti:
```
<div id="breadcrumb">
      <p>Ti trovi in: <span xml:lang="en">Home</span> &gt; &gt; "ALTRAPAGINA"</p>
    </div>
```
Ditemi cosa ne pensate
Grazie a tutti

**Comment by Mirco469** [comment]
Ottimo

**Comment by nfrison** [comment]
Ok

Il Mar 22 Ott 2019, 18:00 Mirco469 <notifications@github.com> ha scritto:
