### ISSUE TITLE
Creazione pagina Successo

### ISSUE THREAD

**Issue by aletomm** [Mirco469/ProgettoSushi#9]
Creazione pagina di avvenuto acquisto/Successo
![image](https://user-images.githubusercontent.com/56229661/66669883-bc2f3b80-ec58-11e9-840b-e4712fd8de97.png)

**Comment by nfrison** [comment]
Pagina di successo con riepilogo ordine effettuato o senza?

**Comment by Mirco469** [comment]
Io personalmente metterei un semplice "Ordine andato a buon fine" o qualcosa del genere

**Comment by aletomm** [comment]
Anch'io metterei solo una scritta con al massimo un'immagine per non fare la pagina completamente vuota
